name: znn_cli_dart
description: Zenon CLI tool
version: 0.0.4
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dcli: ^1.7.1
  znn_sdk_dart:
    git:
      url: https://github.com/sol-sanctum/znn_sdk_dart.git
      ref: acdac5e1eea7a517dfcd71802e374e7402ab99cb # spork_htlc

dev_dependencies:
  test: ^1.17.9
  lints: ^1.0.1
