name: znn_cli_dart
description: Zenon CLI tool
version: 0.0.5
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dcli: ^1.7.1
  znn_sdk_dart:
    path:
      ../znn_sdk_dart
    #git:
    #  url: https://github.com/sol-sanctum/znn_sdk_dart.git
    #  ref: htlc_spork #spork_htlc

dev_dependencies:
  test: ^1.17.9
  lints: ^1.0.1
